// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using data;

#nullable disable

namespace GGStat_Backend.Data.Migrations
{
    [DbContext(typeof(PlayersDBContext))]
    [Migration("20260130094955_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GGStat_Backend.Data.Chat", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int?>("MatchId")
                        .HasColumnType("integer");

                    b.Property<string>("message")
                        .HasColumnType("text");

                    b.Property<string>("player")
                        .HasColumnType("text");

                    b.Property<string>("time")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("MatchId");

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("GGStat_Backend.Data.PlayerData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("alias")
                        .HasColumnType("text");

                    b.Property<string>("avatar")
                        .HasColumnType("text");

                    b.Property<string>("code")
                        .HasColumnType("text");

                    b.Property<string>("flag")
                        .HasColumnType("text");

                    b.Property<string>("league")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("loses")
                        .HasColumnType("integer");

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.Property<int>("points")
                        .HasColumnType("integer");

                    b.Property<string>("race")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("region")
                        .HasColumnType("text");

                    b.Property<int>("standing")
                        .HasColumnType("integer");

                    b.Property<int>("wins")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("PlayerData");
                });

            modelBuilder.Entity("Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PlayerDataId")
                        .HasColumnType("integer");

                    b.Property<string>("duration")
                        .HasColumnType("text");

                    b.Property<string>("map")
                        .HasColumnType("text");

                    b.Property<string>("match_id")
                        .HasColumnType("text");

                    b.Property<string>("match_link")
                        .HasColumnType("text");

                    b.Property<string>("opponent")
                        .HasColumnType("text");

                    b.Property<string>("opponent_race")
                        .HasColumnType("text");

                    b.Property<string>("player_race")
                        .HasColumnType("text");

                    b.Property<int>("points")
                        .HasColumnType("integer");

                    b.Property<string>("result")
                        .HasColumnType("text");

                    b.Property<string>("timeAgo")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PlayerDataId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("GGStat_Backend.Data.Chat", b =>
                {
                    b.HasOne("Match", null)
                        .WithMany("chat")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Match", b =>
                {
                    b.HasOne("GGStat_Backend.Data.PlayerData", null)
                        .WithMany("matches")
                        .HasForeignKey("PlayerDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GGStat_Backend.Data.PlayerData", b =>
                {
                    b.Navigation("matches");
                });

            modelBuilder.Entity("Match", b =>
                {
                    b.Navigation("chat");
                });
#pragma warning restore 612, 618
        }
    }
}
