version: '3.8'

services:
  web_api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: GGStatContainer
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=maxim12345
      - DB_NAME=GGStatDB
    volumes:
      - nuget_cache:/root/.nuget/packages

  db:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=maxim12345
      - POSTGRES_DB=GGStatDB
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    container_name: GGStatDBContainer
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
  nuget_cache: